# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/mydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50   # Optimal for most apps, adjust if needed
      minimum-idle: 10        # Keep a small number of idle connections
      idle-timeout: 30000     # 30s before releasing idle connections
      connection-timeout: 20000 # 20s to get a connection before failing
      max-lifetime: 1800000   # 30 min max connection age
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent-output: true
    deserialization:
      fail-on-unknown-properties: true

server:
  tomcat:
    threads:
      max: 200         # Reduce to avoid overloading DB
      min-spare: 20
  connection-timeout: 20000 # 20s request timeout


